# Generated by Django 5.0.6 on 2024-05-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pic',
            field=models.FileField(upload_to='GWFVDPMB'),
        ),
    ]
