# Generated by Django 5.0.6 on 2024-05-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
