# Generated by Django 5.0.6 on 2024-05-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientFaces',
        ),
    ]
