# Generated by Django 5.0.6 on 2024-05-12 15:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_client_clientfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfaces',
            name='pic',
            field=models.FileField(upload_to=api.models.upload_to_path_face),
        ),
        migrations.AlterField(
            model_name='room',
            name='pic',
            field=models.FileField(upload_to=api.models.upload_to_path),
        ),
    ]
