# Generated by Django 5.0.6 on 2024-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='pic',
            field=models.FilePathField(),
        ),
    ]
