# Generated by Django 5.0.6 on 2024-05-14 12:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_matches_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='pic',
            field=models.ImageField(upload_to=api.models.upload_to_matched_face),
        ),
    ]
